### ISSUE TITLE
The zoom bar won't lock

### ISSUE THREAD

**Issue by Patacon420** [alaahadid/AHD-Subtitles-Maker#1]
I love this software and I recently bought a new PC and got the latest version 5.23.7818.13246.
The problem is that when I set the zoom bar in 35, which is my ideal zoom to work, it changes to the max value when I edit any subtitle. This is really annoying and I can't work adjusting the zoom bar back to 35 continuously. Help me solve this issue, please.

**Comment by alaahadid** [comment]
Hello,
I think this issue is fixed in the [new version 5.24.7901.42251](https://github.com/alaahadid/AHD-Subtitles-Maker/releases/tag/v5.24.7901.42251). Please feel free to let me know if everything is ok with this new release 👍

**Comment by Patacon420** [comment]
Amazing, Mr. Hadid, it works now, thanks!

**Comment by alaahadid** [comment]
Glad it is working now 👍 
This topic is closed after confirmation that the issue has been resolved.
